// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// FormErrorCode form error code
// swagger:model FormErrorCode
type FormErrorCode string

// Validate validates this form error code
func (m FormErrorCode) Validate(formats strfmt.Registry) error {
	return nil
}
