// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// RequestMethodConfig request method config
// swagger:model RequestMethodConfig
type RequestMethodConfig struct {

	// get form fields
	GetFormFields FormFields `json:"GetFormFields,omitempty"`
}

// Validate validates this request method config
func (m *RequestMethodConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGetFormFields(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RequestMethodConfig) validateGetFormFields(formats strfmt.Registry) error {

	if swag.IsZero(m.GetFormFields) { // not required
		return nil
	}

	if err := m.GetFormFields.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("GetFormFields")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RequestMethodConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestMethodConfig) UnmarshalBinary(b []byte) error {
	var res RequestMethodConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
